---
- name: Check if Helm is already installed
  ansible.builtin.command: which helm
  register: helm_check
  changed_when: false
  failed_when: false

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_check.rc != 0

- name: Run Helm install script
  ansible.builtin.command: /tmp/get_helm.sh
  when: helm_check.rc != 0

- name: Remove Helm install script
  ansible.builtin.file:
    path: /tmp/get_helm.sh
    state: absent
  when: helm_check.rc != 0

- name: Verify Helm installation
  ansible.builtin.command: helm version
  register: helm_version
  changed_when: false

- name: Display Helm version
  ansible.builtin.debug:
    msg: "{{ helm_version.stdout }}"
