---

- name: Add worker node
  become: yes
  shell: |
    kubeadm join {{ hostvars[groups['master'][0]].ansible_host }}:6443 --token={{ kube_token }} --discovery-token-ca-cert-hash {{ kube_crt }}
    touch /etc/kubernetes/ansible-joined
  args:
    creates: /etc/kubernetes/ansible-joined
