---
# - name: Create cert-manager namespace
#   kubernetes.core.k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Namespace
#       metadata:
#         name: cert-manager

- name: Add Jetstack Helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

# - name: Install cert-manager CRDs
#   ansible.builtin.shell: |
#     kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.crds.yaml
#   args:
#     executable: /bin/bash
#   register: crds_result
#   changed_when: "'created' in crds_result.stdout or 'configured' in crds_result.stdout"

- name: Install cert-manager via Helm
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    # chart_repo_url: https://charts.jetstack.io
    release_namespace: cert-manager
    create_namespace: true
    wait: true
    chart_version: "v1.18.0"
    set_values:
      - value: crds.enabled=true
