---

- name: apt install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add GPG key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: apt install docker packages
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name:  Add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes

- name: Verify that the docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes
