---
- hosts: 
    - master
    - worker
  tags: ['init']
  become: true
  roles:
    - apt
    - kubeadm
  gather_facts: true

- hosts:
    - master
  become: true
  tags: ['deploy', 'deploy_master']
  roles:
    - master_node

- hosts:
    - master
  become: true
  tags: ['deploy', 'deploy_cni_calico']
  roles:
    - calico

- hosts:
    - worker
  become: true
  tags: ['deploy', 'deploy_worker']
  roles:
    - worker_node
