---
- name: Configure nodes
  hosts:
    - master
    - worker
  tags: ['init']
  become: true
  roles:
    - apt
    - kubeadm
    - ansible-kube
    - helm
  gather_facts: true

- name: Provision Master
  hosts:
    - master
  become: true
  tags: ['provision', 'provision-master']
  roles:
    - master-node

- name: Provision Worker
  hosts:
    - worker
  become: true
  tags: ['provision', 'provision-workers']
  roles:
    - worker-node

# Install

- name: Install helm
  hosts:
    - master
  tags: ['install', 'install-helm']
  roles:
    - helm


- name: Install cilium
  hosts:
    - master
  tags: ['install', 'install-cni-cilium']
  roles:
    - cilium

- name: Install argocd
  hosts:
    - master
  tags: ['install', 'install-argocd']
  roles:
    - argocd

- name: Install cert-manager
  hosts:
    - master
  tags: ['install', 'install-cert-manager']
  roles:
    - cert-manager

- name: Install monitoring
  hosts:
    - master
  tags: ['install', 'install-monitoring']
  roles:
    - monitoring
