---
- name: Configure nodes
  hosts:
    - master
    - worker
  tags: ['init']
  become: true
  roles:
    - apt
    - kubeadm
    - ansible-kube
  gather_facts: true

- name: Configure ansible kube
  hosts:
    - master
    - worker
  tags: ['init', 'ansible-kube']
  roles:
    - ansible-kube
  gather_facts: true

- name: Provision Master
  hosts:
    - master
  become: true
  tags: ['deploy', 'deploy_master']
  roles:
    - master_node

- name: Deploy flannel
  hosts:
    - master
  become: true
  tags: ['deploy', 'deploy_cni_flannel']
  roles:
    - flannel

- name: Deploy argocd
  hosts:
    - master
  tags: ['deploy', 'deploy_argocd']
  roles:
    - argocd

- name: Init Worker
  hosts:
    - worker
  become: true
  tags: ['deploy', 'deploy_worker']
  roles:
    - worker_node
